//Vue.component('v-select', VueSelect.VueSelect);
var vm = new Vue({
    el: '#main',
    data: {
        modulo:{},
        accion:''
    },

    methods: {
        /**boton de modal Guardar*/
        guardarModulo: function () {
            if (vm.accion=='nuevo') {
                vm.modulo.modulo_id=0;
                Modulos.store();
            } else {
                Modulos.update(vm.modulo.id);
            }
        },
        /**boton llama a modal, nuevo rol */
        storeModulo: function () {
            $("#moduloModal").modal();
            vm.accion = 'nuevo';
            vm.modulo = {};
        },
    },
});

var tabla='datatable_tabletools';

/* BASIC ;*/
var responsiveHelper_datatable_tabletools = undefined;

var $selectModulos;
//var $selectRoles;

var breakpointDefinition = {
    tablet : 1024,
    phone : 480
};

var columnDefs=[
    {
        "targets": 0,
        "data": "id",
        "name": "id",
        "searchable":false
    },
    {
        "targets": 1,
        "data": "nombre",
        "name": "nombre"
    },
    {
        "targets": 2,
        "data": "url",
        "name": "url"
    },
    {
        "targets": 3,
        "data": "icon",
        "name": "icon",
        "searchable":false
    },
    {
        "targets": 4,
        "name": "updated_at",
        "searchable":false,
        "data": function ( row, type, val, meta ) {
            return '<td><button type="button" onClick="editar('+row.id+')" class="btn btn-primary">Editar</button></td>';
        },
        "defaultContent": '',
    },
    {
        "targets": 5,
        "name": "deleted_at",
        "searchable":false,
        "data": function ( row, type, val, meta ) {
            estado='<button type="button"  onClick="activar('+row.id+')" class="btn btn-success">Inactivo</button>';
            if (row.deleted_at===null){
                estado='<button type="button" onClick="desactivar('+row.id+')" class="btn btn-success">Activo</button>';
            }
            return estado;
        },
        "defaultContent": '',
    }
];

var dataTable={
    "processing": true,
    "serverSide": true,
    "stateSave": true,
    "searching": true,
    "ordering": true,
    "stateLoadCallback": function (settings) {
        $("body").append('<div class="overlay"></div><div class="loading-img"></div>');
    },
    "stateSaveCallback": function (settings) { // Cuando finaliza el ajax
        $(".overlay,.loading-img").remove();
    },
    "ajax": {
        "url": "api/modulos",
        "type": "GET",
        "data": function(d){
            d.per_page=d.length;
            d.page=(d.start+d.length)/d.length;
            d.filter=d.search.value;
        },
    },
    columnDefs,
    "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>"+
            "t"+
            "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
    "oLanguage": {
        "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
    },
    "oTableTools": {
        "aButtons": [
            "copy",
            "csv",
            "xls",
            {
                "sExtends": "pdf",
                "sTitle": "SmartAdmin_PDF",
                "sPdfMessage": "SmartAdmin PDF Export",
                "sPdfSize": "letter"
            },
            {
                "sExtends": "print",
                "sMessage": "Generated by SmartAdmin <i>(press Esc to close)</i>"
            }
        ],
        "sSwfPath": "js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
    },
    "autoWidth" : true,
    "preDrawCallback" : function() {
        if (!responsiveHelper_datatable_tabletools) {
            responsiveHelper_datatable_tabletools = new ResponsiveDatatablesHelper($('#'+tabla), breakpointDefinition);
        }
    },
    "rowCallback" : function(nRow,data) {
        responsiveHelper_datatable_tabletools.createExpandIcon(nRow);
    },
    "drawCallback" : function(oSettings) {
        responsiveHelper_datatable_tabletools.respond();
    }
};
var datatable;
$(document).ready(function() {
    pageSetUp();
    datatable = $('#'+tabla).DataTable(dataTable);
});
/**
   boton llama a modal, editar rol
*/
editar=function(id){
    vm.accion='editar';
    Modulos.get(id);
    $("#moduloModal").modal();
};
desactivar=function(id){
    reload();
};
activar=function(id){
    reload();
};
reload=function(){
    datatable.ajax.reload(null,false);
};